services:

  #-----------------------------------
  #---- Private-GPT services ---------
  #-----------------------------------
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvect-rag    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  # Private-GPT service for the OpenAI mode
  # This service builds from an external Dockerfile and runs the OpenAI mode.
  vtt-workshop-rag:    
    user: root
    build:
      context: .
      dockerfile: Dockerfile.openai
    volumes:
      - ./local_data:/home/worker/app/local_data
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: openai
      PGPT_MODE: openai
      PGPT_EMBED_MODE: openai      
      DATABASE_HOST: pgvector
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LEONARDO_API_KEY: ${LEONARDO_API_KEY}
      VTT_WEBHOOK_URL: ${VTT_WEBHOOK_URL}

    depends_on:
      - pgvector 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  